{
 "title": "Ventilation",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Current State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature ",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature_inlet_before_recuperator{}",
     "legendFormat": "inlet before recup."
    },
    {
     "expr": "temperature_inlet_after_recuperator{}",
     "legendFormat": "inlet after recup."
    },
    {
     "expr": "temperature_outlet_before_recuperator{}",
     "legendFormat": "outlet before recup."
    },
    {
     "expr": "temperature_outlet_after_recuperator{}",
     "legendFormat": "outlet after recup."
    }
   ]
  },
  {
   "title": "Humidity ",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_humidity_inlet_before_recuperator{}",
     "legendFormat": "inlet before recup."
    },
    {
     "expr": "air_humidity_inlet_after_recuperator{}",
     "legendFormat": "inlet after recup."
    },
    {
     "expr": "air_humidity_outlet_before_recuperator{}",
     "legendFormat": "outlet before recup."
    },
    {
     "expr": "air_humidity_outlet_after_recuperator{}",
     "legendFormat": "outlet after recup."
    }
   ]
  },
  {
   "title": "Supply Fan Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speed_input_ventilator{}" }
   ]
  },
  {
   "title": "Supply Air Vol ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "air_volume_input_ventilator{}" }
   ]
  },
  {
   "title": "Supply Fan Duty",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "power_percent_input_ventilator{}"
    }
   ]
  },
  {
   "title": "Bypass ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bypass_state{}" }
   ]
  },
  {
   "title": "Extract Fan Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speed_output_ventilator{}" }
   ]
  },
  {
   "title": "Extract Air Vol ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "air_volume_input_ventilator{}" }
   ]
  },
  {
   "title": "Extract Fan Duty",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "power_percent_output_ventilator{}"
    }
   ]
  },
  {
   "title": "Bypass ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ventilation_level{}" }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temperature_inlet_before_recuperator{}",
     "legendFormat": "inlet before recup."
    },
    {
     "expr": "temperature_inlet_after_recuperator{}",
     "legendFormat": "inlet after recup."
    },
    {
     "expr": "temperature_outlet_before_recuperator{}",
     "legendFormat": "outlet before recup."
    },
    {
     "expr": "temperature_outlet_after_recuperator{}",
     "legendFormat": "outlet after recup."
    }
   ]
  },
  {
   "title": "Humidity ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "air_humidity_inlet_before_recuperator{}",
     "legendFormat": "inlet before recup."
    },
    {
     "expr": "air_humidity_inlet_after_recuperator{}",
     "legendFormat": "inlet after recup."
    },
    {
     "expr": "air_humidity_outlet_before_recuperator{}",
     "legendFormat": "outlet before recup."
    },
    {
     "expr": "air_humidity_outlet_after_recuperator{}",
     "legendFormat": "outlet after recup."
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    { "expr": "speed_input_ventilator{}", "legendFormat": "Supply" },
    { "expr": "speed_output_ventilator{}", "legendFormat": "Extract" }
   ]
  },
  {
   "title": "Air Volume",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    { "expr": "air_volume_input_ventilator{}", "legendFormat": "Supply" },
    { "expr": "air_volume_output_ventilator{}", "legendFormat": "Extract" }
   ]
  },
  {
   "title": "Fan Duty",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "power_percent_input_ventilator{}",
     "legendFormat": "Supply"
    },
    {
     "expr": "power_percent_output_ventilator{}",
     "legendFormat": "Extract"
    }
   ]
  }
 ]
}